In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame

file_path = Path("lending_data.csv")
data = pd.read_csv(file_path)

# Review the DataFrame
print(data.head())  # Display the first few rows of the DataFrame
print(data.info())  # Display information about the DataFrame (column names, data types, non-null values, etc.)

   loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77536 entries, 0 to 77535
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   loan_size         77536 

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = data['loan_status']

# Separate the X variable, the features
X = data.drop(columns=['loan_status'])  # Drop the 'loan_status' column to keep only the features


In [4]:
# Review the y variable Series
print(y)


0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [5]:
# Review the X variable DataFrame - first few rows
print(X.head())

# Review the X variable DataFrame - information
print(X.info())

   loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77536 entries, 0 to 77535
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   loan_size         77536 non-null  float64
 1   interest_rate     77536 non-null  float64
 2   borrower

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
# Check the balance of our target values
print(y.value_counts())


loan_status
0    75036
1     2500
Name: count, dtype: int64


### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
# Import the train_test_split function from sklearn.model_selection
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Print the shapes of the training and testing datasets
print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Testing labels shape:", y_test.shape)


Training features shape: (62028, 7)
Testing features shape: (15508, 7)
Training labels shape: (62028,)
Testing labels shape: (15508,)


---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Step 1: Instantiate the Logistic Regression model
logistic_regression_model = LogisticRegression(random_state=1)

# Step 2: Fit the model using training data
logistic_regression_model.fit(X_train, y_train)


LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
# Step 2: Make a prediction using the testing data
y_pred = logistic_regression_model.predict(X_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [10]:
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

# Step 3: Print the balanced_accuracy score of the model
balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy Score:", balanced_accuracy)

# Generate a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print the classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


Balanced Accuracy Score: 0.9668615123225841
Confusion Matrix:
[[14924    77]
 [   31   476]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.86      0.94      0.90       507

    accuracy                           0.99     15508
   macro avg       0.93      0.97      0.95     15508
weighted avg       0.99      0.99      0.99     15508



In [11]:
from sklearn.metrics import confusion_matrix

# Generate a confusion matrix for the model
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[14924    77]
 [   31   476]]


In [12]:
from sklearn.metrics import classification_report

# Print the classification report for the model
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.86      0.94      0.90       507

    accuracy                           0.99     15508
   macro avg       0.93      0.97      0.95     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** Based on the evaluation metrics obtained from the logistic regression model, we can assess its performance in predicting both the 0 (healthy loan) and 1 (high-risk loan) labels:

1. **Accuracy Score**: The accuracy score provides an overall measure of the model's correctness in predicting both classes. However, it may not be the best metric for imbalanced datasets. A high accuracy score indicates that the model performs well in predicting both classes.

2. **Confusion Matrix**: The confusion matrix breaks down the model's predictions into four categories: true positives (TP), false positives (FP), true negatives (TN), and false negatives (FN). By examining the values in the matrix, we can see how well the model predicts each class. For example, a high number of true positives and true negatives indicates good performance in predicting both healthy and high-risk loans.

3. **Classification Report**: The classification report provides metrics such as precision, recall, and F1-score for each class. Precision measures the proportion of true positives among all positive predictions, recall measures the proportion of true positives identified correctly, and the F1-score is the harmonic mean of precision and recall. A high F1-score indicates that the model performs well in predicting both classes.

Overall, by analyzing these metrics, we can determine how well the logistic regression model predicts both healthy and high-risk loans. If the model achieves high accuracy, balanced values in the confusion matrix, and high precision, recall, and F1-score in the classification report for both classes, it indicates good predictive performance for both label types.

In [13]:
pip install --upgrade scikit-learn imbalanced-learn

^C
Note: you may need to restart the kernel to use updated packages.


---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [14]:
import sklearn
import imblearn

# Step 1: Import the RandomOverSampler module from imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
random_oversampler = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = random_oversampler.fit_resample(X_train, y_train)


In [15]:
# Count the distinct values of the resampled labels data
print(y_resampled.value_counts())


loan_status
0    60035
1    60035
Name: count, dtype: int64


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [16]:
# Step 2: Instantiate the Logistic Regression model
logistic_regression_model_resampled = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
logistic_regression_model_resampled.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
y_pred_resampled = logistic_regression_model_resampled.predict(X_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [17]:
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

# Calculate the balanced_accuracy score of the model
balanced_accuracy_resampled = balanced_accuracy_score(y_test, y_pred_resampled)
print("Balanced Accuracy Score:", balanced_accuracy_resampled)

# Generate a confusion matrix
conf_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
print("Confusion Matrix:")
print(conf_matrix_resampled)

# Print the classification report
class_report_resampled = classification_report(y_test, y_pred_resampled)
print("Classification Report:")
print(class_report_resampled)


Balanced Accuracy Score: 0.9941416134387885
Confusion Matrix:
[[14914    87]
 [    3   504]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.85      0.99      0.92       507

    accuracy                           0.99     15508
   macro avg       0.93      0.99      0.96     15508
weighted avg       0.99      0.99      0.99     15508



In [18]:
from sklearn.metrics import confusion_matrix

# Generate a confusion matrix for the model
conf_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
print("Confusion Matrix:")
print(conf_matrix_resampled)


Confusion Matrix:
[[14914    87]
 [    3   504]]


In [19]:
from sklearn.metrics import classification_report

# Print the classification report for the model
class_report_resampled = classification_report(y_test, y_pred_resampled)
print("Classification Report:")
print(class_report_resampled)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.85      0.99      0.92       507

    accuracy                           0.99     15508
   macro avg       0.93      0.99      0.96     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The evaluation metrics obtained from the logistic regression model fit with oversampled data provide insights into its predictive performance for both the 0 (healthy loan) and 1 (high-risk loan) labels:

1. **Balanced Accuracy Score**: This metric provides an overall measure of the model's correctness in predicting both classes. A higher balanced accuracy score indicates better performance in predicting both healthy and high-risk loans.

2. **Confusion Matrix**: The confusion matrix breaks down the model's predictions into four categories: true positives (TP), false positives (FP), true negatives (TN), and false negatives (FN). By examining the values in the matrix, we can assess how well the model predicts each class. A balanced distribution of TP and TN values across both classes indicates good predictive performance.

3. **Classification Report**: The classification report provides metrics such as precision, recall, and F1-score for each class. Precision measures the proportion of true positives among all positive predictions, recall measures the proportion of true positives identified correctly, and the F1-score is the harmonic mean of precision and recall. Higher values of precision, recall, and F1-score indicate better predictive performance for both classes.

Based on these metrics, we can conclude how effectively the logistic regression model, fit with oversampled data, predicts both healthy and high-risk loans. If the model achieves high balanced accuracy, balanced values in the confusion matrix, and high precision, recall, and F1-score in the classification report for both classes, it indicates good predictive performance for both label types.